apiVersion: v1
kind: Pod # 定义Kubernetes资源的类型为Pod
metadata:
  name: k8s-net-pod # 定义资源的名称
  labels:
    app: k8s-net-pod
spec: # 定义资源的状态，对于Pod来说，最重要属性就是containers
  containers: # containers一个数组类型，如果你希望部署多个容器，可以添加多项
    - name: web # 定义本Pod中该容器的名称
      image: test_project/v1 # 定义Pod启动的容器镜像地址
      imagePullPolicy: IfNotPresent # k8s默认值为Always，总是从远端拉取镜像，通过设置IfNotPresent或Never来使用本地镜像
      ports:
        - containerPort: 80 # 定义容器监听的端口（与Dockerfile中的EXPOSE类似，只是为了提供文档信息）
      livenessProbe: # 存活探针定义
        httpGet:
          path: /host/CheckHealth # healthyCheck路徑
          port: 80
          initialDelaySeconds: 15 # 服務啟動後 幾秒後做healthyCheck      預設=0 最小設定=0
          periodSeconds: 15       # 每隔幾秒Check一次                    預設=10 最小設定=1
          timeoutSeconds: 30      # timeout時間                         預設=1 最小設定=1
          successThreshold: 1     # 呼叫幾次成功後 會更改狀態回success    預設=1 最小設定=1
          failureThreshold: 3     # 呼叫幾次失敗後 會更改狀態回failure    預設=1 最小設定=1
  nodeSelector:
    SpecifyNode: node_test1