apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller
spec:
  replicas: 3
  selector:
    app: k8s-net-pod
  template:
    metadata:
      labels:
        app: k8s-net-pod
    spec:
      containers:
      - name: web
        image: test_project/v1 # 定义Pod启动的容器镜像地址
        imagePullPolicy: IfNotPresent # k8s默认值为Always，总是从远端拉取镜像，通过设置IfNotPresent或Never来使用本地镜像
        ports:
        - containerPort: 80 # 定义容器监听的端口（与Dockerfile中的EXPOSE类似，只是为了提供文档信息）